project3/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rock.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rock/urls.py
from django.urls import path

from . import views

app_name = 'rock'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('song/list/', views.SongListView.as_view(), name='song-list'),
    path('song/<slug:slug>/', views.SongDetailView.as_view(), name='song-detail'),
    path('group/list/', views.GroupListView.as_view(), name='group-list'),
    path('group/<int:pk>/', views.GroupDetailView.as_view(), name='group-detail'),

    path('user/sign/out/', views.user_sign_out, name='user-sign-out'),
    path('login/page', views.login_page, name='login-page'),
    path('user/sign/in/', views.user_sign_in, name='user-sign-in'),

    path('search/', views.search, name='search'),
    path('song/comment/<int:pk>/', views.add_comment, name='add-comment'),
    path('song/playlist/<int:pk>/', views.change_playlist_song_status, name='playlist-change'),

    path('api/song/list/', views.SongListAPIView.as_view(), name='api-song-list'),
]

rock/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

from django.utils import timezone
from taggit.managers import TaggableManager


class Group(models.Model):
    name = models.CharField(max_length=128)
    member1 = models.CharField(max_length=128, null=True, blank=True)
    member2 = models.CharField(max_length=128, null=True, blank=True)
    member3 = models.CharField(max_length=128, null=True, blank=True)
    member4 = models.CharField(max_length=128, null=True, blank=True)
    member5 = models.CharField(max_length=128, null=True, blank=True)
    member6 = models.CharField(max_length=128, null=True, blank=True)
    member7 = models.CharField(max_length=128, null=True, blank=True)
    portrait = models.ImageField(upload_to='groups/', null=True, blank=True)
    formed = models.IntegerField()
    history = models.FileField(upload_to='histories/', blank=True, null=True)
    # songs

    def __str__(self):
        return self.name

    def url_detail(self):
        return reverse('rock:group-detail', kwargs={
            'pk': self.id,
        })

    class Meta:
        ordering = ['name']

class Song(models.Model):
    title = models.CharField(max_length=128)
    year = models.IntegerField()
    rating = models.FloatField(default=5.0)
    poster = models.ImageField(upload_to='posters/', blank=True, null=True)
    group = models.ForeignKey(Group, related_name='songs', on_delete=models.SET_NULL,
                                 null=True, blank=True)
    trailer = models.CharField(max_length=11, blank=True, null=True)
    slug = models.SlugField(blank=True, null=True)
    tags = TaggableManager()
    wishing_to_listen = models.ManyToManyField(User, blank=True, related_name='playlist')
    # user_ratings

    def __str__(self):
        return self.title

    def url_detail(self):
        return reverse('rock:song-detail', kwargs={
            'slug': self.slug,
        })

    def genres_str(self):
        return ' '.join(t.name for t in self.tags.all())

    def number_of_other_wishing_to_listen(self):
        return self.wishing_to_listen.count() - 1

    def users_made_rating(self):
        return User.objects.filter(ratings__song=self).all()

    class Meta:
        ordering = ['title']


class Addon(models.Model):
    user = models.OneToOneField(User, related_name='addon', on_delete=models.CASCADE)
    userpic = models.ImageField(upload_to='userpics/', blank=True, null=True)


class Comment(models.Model):
    text = models.CharField(max_length=512)
    song = models.ForeignKey(Song, related_name='comments', on_delete=models.CASCADE)
    published = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(User, related_name='comments', on_delete=models.CASCADE)

    class Meta:
        ordering = ['-published']

rock/forms.py
from django.forms import ModelForm, TextInput

from .models import *

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            "text": TextInput(attrs={"placeholder": 'Your Comment'}),
        }

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['text'].label = ""
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

rock/views.py
from django.contrib.auth import logout, authenticate, login
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from django.db.models import Avg, Count
from django.db.models import Q

from rest_framework import generics

from random import choice

from .models import *
from .serializers import *
from .forms import *


class HomeView(TemplateView):
    template_name = 'rock/index.html'
    extra_context = {
        # 'songs': Song.objects.all(),
        'songs': Song.objects.order_by('-rating')[:4],
        'groups': Group.objects.annotate(rating=Avg('songs__rating')).order_by('-rating')[:3],
    }


class SongListView(ListView):
    model = Song
    paginate_by = 3


class GroupListView(ListView):
    model = Group
    queryset = Group.objects.annotate(rating=Avg('songs__rating')).order_by('name')


class SongDetailView(DetailView):
    model = Song
    # extra_context = {
    #     'c_form': CommentForm(),
    # }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['c_form'] = CommentForm()
        context['similar_songs'] = Song.objects.filter(tags__in=self.object.tags.all()).distinct()\
            .exclude(id=self.object.id).annotate(number_of_tags=Count('tags')).order_by('-number_of_tags')[:3]
        return context


class GroupDetailView(DetailView):
    model = Group

    def get_context_data(self, **kwargs):
        context = super(GroupDetailView, self).get_context_data(**kwargs)
        context['rating'] = self.object.songs.aggregate(Avg('rating')).get('rating__avg')
        songs = self.object.songs.all()
        context['songs'] = songs
        trailers = self.object.songs.values_list('trailer', flat=True)
        # print(trailers)
        if trailers:
            context['trailer'] = choice(trailers)
        print([context])
        return context

def user_sign_out(request):
    next = request.GET.get('next')
    print('next', next)
    logout(request)
    return HttpResponseRedirect(next)


def login_page(request):
    next = request.GET.get('next')
    return render(request,
                  template_name='rock/login_page.html',
                  context= {
                      'next': next,
                  })


def user_sign_in(request):
    next = request.POST.get('next')
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(request, username=username, password=password)
    if user:
        login(request, user)
        return HttpResponseRedirect(next)
    else:
        return render(request,
               template_name='rock/login_page.html',
               context={
                   'next': next,
                   'message': 'Incorrect username or password',
                   'last_username': username,
               })


def change_playlist_song_status(request, pk):
    song = Song.objects.get(pk=pk)
    user = request.user
    if song.wishing_to_listen.contains(user):
        song.wishing_to_listen.remove(user)
    else:
        song.wishing_to_listen.add(user)
    return HttpResponseRedirect(song.url_detail())


class SongListAPIView(generics.ListAPIView):
    serializer_class = SongSerializer1
    queryset = Song.objects.all()


def search(request):
    search_str = request.POST.get('search')
    option = request.POST.get('option')
    next = request.POST.get('next')
    if search_str:
        songs = Song.objects.filter(Q(title__icontains=search_str)) if option in '13' else None
        groups = Group.objects.filter(Q(name__icontains=search_str))\
                            .annotate(rating=Avg('songs__rating')).order_by('name') if option in '23' else None
        return render(request,
                      template_name='rock/search_page.html',
                      context={
                          'search': search_str,
                          'songs': songs,
                          'groups': groups,
                      })
    else:
        return HttpResponseRedirect(next)


def add_comment(request, pk):
    song = Song.objects.get(pk=pk)
    f = CommentForm(request.POST)
    if f.is_valid():
        new_comment: Comment = f.save(commit=False)
        print('new_comment', new_comment)
        new_comment.song = song
        new_comment.user = request.user
        new_comment.save()
    else:
        print(f.errors)
    return HttpResponseRedirect(song.url_detail())

rock/templates/rock/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'rock/img/logo1.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
</head>
<body class="bg-danger p-2 text-danger bg-opacity-50">
    <div class="container my-3 my-3">
        <div class="row mb-3">
            <div class="col-1">
                <a href="{% url 'rock:home' %}" class="text-decoration-none">
                    <img src="{% static 'rock/img/logo1.png' %}" class="w-75">
                </a>
            </div>
            <div class="col-1 pt-1">
                <a href="{% url 'rock:song-list' %}" class="text-black text-decoration-none">All Songs</a>
                <br>
                <a href="{% url 'rock:group-list' %}" class="text-black text-decoration-none">All Groups</a>
            </div>
            <div class="col-1 pt-2">
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    Menu
                </button>
            </div>
            <div class="col-7 pt-2">
                <form action="{% url 'rock:search' %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-2">
                            <select class="form-select" aria-label="Default select example" name="option">
                                <option value="3" selected>All</option>
                                <option value="1">Songs</option>
                                <option value="2">Groups</option>
                            </select>
                        </div>
                        <div class="col-9">
                            <input type="text" name="search" placeholder="Search" class="form-control">
                        </div>
                        <div class="col-1">
                            <button type="submit" class="btn btn-light">
                                <i class="fa-solid fa-magnifying-glass"></i>
                            </button>
                        </div>
                    </div>
                    <input type="hidden" name="next" value="{{ request.path }}">
                </form>
            </div>

            <div class="col-2 pt-2 text-center">
                {% if user.is_authenticated %}
                    {% if user.addon.userpic %}
                    <img src="{{ user.addon.userpic.url }}" width="50">
                    {% else %}
                    {% endif %}
                    <p class="text-white">{{ user }}</p>
                    <a href="{% url 'rock:user-sign-out' %}?next={{ request.path }}" 
                    class="text-primary text-decoration-none">Sign Out</a>
                {% else %}
                    <a href="{% url 'rock:login-page' %}?next={{ request.path }}" 
                    class="text-primary text-decoration-none">Sign In</a>
                {% endif %}
            </div>
        </div>
        {% block main %}{% endblock %}

    </div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">User Menu</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col">
                        <a href="{% url 'rock:song-list' %}" class="text-decoration-none">All songs</a>
                        <br>
                        <a href="{% url 'rock:group-list' %}" class="text-decoration-none">All groups</a>
                        <br>
                        <a href="/api/song/list/" class="text-decoration-none" target="_blank">API songs</a>
                        <br>
                        <a href="/admin/" target="_blank" class="text-decoration-none">Admin Panel</a>
                    </div>
                    <div class="col">
                        {% if user.is_authenticated %}
                        <p>
                            <img src="{{ user.addon.userpic.url }}" width="40" class="border border-white">
                            {{ user.get_full_name }}
                        </p>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>


</body>
</html>

rock/templates/rock/group_detail.html
{% extends 'rock/base.html' %}
{% load static %}

{% block title %}{{ group }}{% endblock %}

{% block main %}

<p class="text-black text-center fs-2"><b>{{ group }}</b></p>

<div class="row my-3 justify-content-between">
    <div class="col-3">
        <p class="text-black fs-4">
            Formed in <b>{{ group.formed }}</b>
        </p>
    </div>
    <div class="col-3">
        <p class="text-light fs-4">
            Overall rating:
            <img src="{% static 'rock/img/star.png' %}" width="30">
            <b>{{ rating|floatformat:1 }}</b>
        </p>
    </div>
</div>

<div class="row my-5 justify-content-between">
    <div class="col-6">
        <img src="{{ group.portrait.url }}" class="w-100 object-fit-contain text-center">
    </div>
    <div class="col-4">
        <p class="text-black text-decoration-none fs-3">Songs:</p>
        {% for s in group.songs.all %}
        <div class="row justify-content-between my-1 border-bottom border-secondary">
            <div class="col-2 p-2">
                <img src="{{ s.poster.url }}" class="h-100 w-100">
            </div>
            <div class="col-6">
                <p class="text-white fs-5">
                    <a href="{{ s.url_detail }}" class="text-black text-decoration-none">
                        <b>{{ s }}</b>
                    </a>
                </p>
            </div>
            <div class="col-2">
                <p class="text-black fs-5">{{ s.year }}</p>
            </div>
        </div>
        {% endfor %}
    
    </div>
</div>

<div class="row my-5">
    <div class="col-6">
        {% if group.history %}
        <p class="text-white" style="text-align: justify;">
            {{ group.history.read.decode }}
        </p>
        <hr class="border border-white">
        {% endif %}
    </div>
</div>



{% endblock %}

rock/templates/rock/group_list.html
{% extends 'rock/base.html' %}
{% load static %}

{% block title %}All Groups{% endblock %}

{% block main %}

<p class="text-black text-center fs-2"><b>All Groups</b></p>

<div class="row">
{% for g in object_list %}

<div class="col-6 mb-1 pb-4">
    <a href="{{ g.url_detail }}" class="text-decoration-none">
    <p class="text-danger text-center fs-4"><b>{{ g.name }}</b></p>
    </a>
    <img src="{{ g.portrait.url }}" class="h-75 w-100 rounded p-2 mb-1 border border-black">
    <p class="text-white text-center fs-5">
        <img src="{% static 'rock/img/star.png' %}" width="30">
        Overall rating: <b>{{ g.rating|floatformat:1 }}</b></p>
        
</div>
{% endfor %}
</div>

{% endblock %}

rock/templates/rock/index.html
{% extends 'rock/base.html' %}
{% load static %}

{% block title %}American Rock Groups{% endblock %}

{% block main %}


<div class="row mt-6 justify-content-around">
    <main role="main">
        <section class="jumbotron text-center">
            <div class="container">
                <h1 class="jumbotron-heading"><b>American Rock Groups</b></h1>
                <p class="lead text-black mt-4">"Good music comes out of people playing together, knowing what they want to
                    do and going for it."
                    <br>
                    - Keith Richards.
                </p>
            </div>
        </section>
</div>


<p class="text-black text-center fs-3 mt-5 mb-5"><b>My Favourite Groups</b></p>
{% for g in groups %}
<div class="card-center row row-cols-md-1 mx-5 px-5 mb-3 text-center">
    <div class="col-3">
        <div class="card mb-4 rounded-3 border-black shadow-sm">
            <div class="card-header py-3 text-bg-danger p-2 text-dark bg-opacity-75 border-black">
                <h4 class="my-0">
                    <a href="{{ g.url_detail }}" class="text-decoration-none">
                        <p class="text-light fs-3 pt-2"><b>{{ g.name }}</b></p>
                    </a>
                </h4>
            </div>
        <p class="text-black fs-4">
            <img src="{{ g.portrait.url }}" class="h-75 w-75 p-2 mb-1">
        <h1 class="text-black text-center fs-3"><b>Formed in </b><small class="card-title"><b>{{ g.formed }}</b></small>
        </h1>
        </p>
        <button type="button" class="w-100 btn btn-lg btn-outline-danger">
            <a href="{{ g.url_detail }}" class="text-decoration-none">
                <p class="text-black text-center fs-4 mb-1">More about this group</p>
            </a>        
        </button>
        </div>
    </div>
</div>
{% endfor %}
</main>


<p class="text-black text-center fs-3 mt-5 pt-4 mb-5"><b>My Favourite Songs</b></p>
<div class="row">
    {% for s in songs %}
    <div class="col">
        <img src="{{ s.poster.url }}" class="h-75 w-100 rounded p-2 mb-1 border border-black">
        <p class="text-light fs-4">
            <img src="{% static 'rock/img/star.png' %}" width="30">
            {{ s.rating }}
        </p>
        <a href="{{ s.url_detail }}" class="text-decoration-none">
            <p class="text-light fs-5">{{ s.title }}</p>
        </a>
        {% if s.trailer %}
        <a href="https://youtu.be/{{ s.trailer }}" target="_blank" class="text-warning text-decoration-none">
            <img src="{% static 'rock/img/play.png' %}" width="25">
            Watch trailer
        </a>
        {% endif %}
    </div>
    {% endfor %}
</div>


{% if user.is_authenticated and user.playlist.exists %}
<p class="text-black fs-3 mt-5 pt-5 pb-3 mb-5"><b>{{ user }}'s playlist:</b></p>
<div class="row">
{% for s in user.playlist.all %}

<div class="col-2">
    <img src="{{ s.poster.url }}" class="h-50 w-75 rounded p-2 mb-1 border border-black">
    <p class="text-light fs-4">
        <img src="{% static 'rock/img/star.png' %}" width="30">
        {{ s.rating }}
    </p>
    <a href="{{ s.url_detail }}" class="text-decoration-none">
        <p class="text-light fs-5">{{ s.title }}</p>
    </a>
    
</div>
{% endfor %}
</div>
{% endif %}


<footer class="text-body-primary py-5 mt-5 mb-5 text-decoration-none">
    <div class="col-2 text-primary">
        <p class="float-end text-decoration-none fs-4 mb-1">
            <a href="">Back to the top</a>
        </p>
    </div>
</footer>


{% endblock %}

rock/templates/rock/login_page.html
{% extends 'rock/base.html' %}
{% load static %}

{% block title %}User Authentication{% endblock %}

{% block main %}

<p class="text-black fs-3 mt-5"><b>User Authentication</b></p>

<div class="row my-3 justify-content-between">
    <div class="col-3 text-black">
        <form action="{% url 'rock:user-sign-in' %}" method="post">
            {% csrf_token %}
            <div class="my-2">
                <label for="">Username</label>
                <input type="text" name="username" class="form-control" value="{{ last_username }}">
            </div>
            <div class="my-2">
                <label for="">Password</label>
                <input type="password" name="password" class="form-control">
            </div>
            <div class="my-4 d-grid gap-2">
                <input type="submit" value="Sign In" class="btn btn-warning">
            </div>
            <input type="hidden" name="next" value="{{ next }}">
            {% if message %}
            <p class="text-black">
                {{ message }}
            </p>
            {% endif %}
        </form>
    </div>
</div>


{% endblock %}

rock/templates/rock/search_page.html
{% extends 'rock/base.html' %}
{% load static %}

{% block title %}search{% endblock %}

{% block main %}

<p class="text-black fs-2"><b>Search by "{{search}}":</b></p>

{% if songs %}

<p class="text-white fs-4">Found songs ({{songs|length}}):</p>

<div class="row">
    {% for s in songs %}

    <div class="col-3">
        <img src="{{ s.poster.url }}" class="h-75 w-100 rounded p-2 mb-1 border border-black">
        <p class="text-white fs-5">
            <img src="{% static 'rock/img/star.png' %}" width="30">
            {{ s.rating }}
        </p>
        <a href="{{ s.url_detail }}" class="text-decoration-none">
            <p class="text-black fs-5"><b>{{ s.title }}</b></p>
        </a>
    </div>
    {% endfor %}
</div>

{% endif %}


{% if groups %}

<p class="text-white fs-4 mt-5">Found groups ({{groups|length}}):</p>

<div class="row">
    {% for g in groups %}

    <div class="col-3 mb-3">
        <img src="{{ g.portrait.url }}" class="h-75 w-100 rounded p-2 mb-1 border border-black">
        <p class="text-white fs-5">
            <img src="{% static 'rock/img/star.png' %}" width="30">
            {{ g.rating|default_if_none:"0.0"|floatformat:1 }}
        </p>
        <a href="{{ g.url_detail }}" class="text-decoration-none">
            <p class="text-black fs-5"><b>{{ g }}</b></p>
        </a>
    </div>
    {% endfor %}
</div>

{% endif %}



{% endblock %}

rock/templates/rock/song_detail.html
{% extends 'rock/base.html' %}
{% load static %}

{% block title %}{{ song }}{% endblock %}

{% block main %}

<p class="text-black text-center fs-3"><b>{{ song }}</b></p>

<div class="row my-5 justify-content-between">
    <div class="col-5">
        <p class="text-black fs-4">
            Released in <b>{{ song.year }}</b>
        </p>
        <p class="text-light fs-3">
            {% if user.is_authenticated %}
            {% if song in user.playlist.all %}
            {% if song.number_of_other_wishing_to_listen %}
            <span class="text-white fw-light fs-5">
                This song wants to be listened by {{ song.number_of_other_wishing_to_listen }}
                other user{{ song.number_of_other_wishing_to_listen|pluralize }}
            </span>
            {% endif %}
            <a href="{% url 'rock:playlist-change' pk=song.id %}" class="btn btn-warning text-decoration-none">
                <i class="fa-solid fa-check"></i>
                <b>In Playlist</b>
            </a>
            {% else %}
            <a href="{% url 'rock:playlist-change' pk=song.id %}" class="btn btn-outline-warning text-decoration-none">
                <i class="fa-solid fa-plus"></i>
                Add to playlist
            </a>
            {% endif %}
            {% endif %}
        </p>
        <img src="{{ song.poster.url }}" class="h-75 w-100 rounded p-2 mb-1 border border-black">
    </div>
    <div class="col-6 text-end">
        <div class="row my-5 justify-content-between">
            <iframe width="700" height="400"
                src="https://www.youtube.com/embed/{{ song.trailer|default_if_none:'kLDIAVN4Vw0' }}"
                title="YouTube video player" frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                allowfullscreen></iframe>
            <p class="text-black text-center fs-4 mt-4">
                tags:
                {% for tag in song.tags.all %}
                <a href="#" class="btn btn-outline-white text-decoration-none fs-5 mb-1">
                    {{ tag.name }}
                </a>
                {% endfor %}
                <br>
                <p class="text-black text-center text-decoration-none fs-3 mt-1">
                Group
                <a href="{{ song.group.url_detail }}" class="text-primary text-decoration-none">
                {{ song.group }}
                </a></p>
            
        </p>
        </div>
    </div>
</div>


<div class="col-6 my-5 justify-content-between">
        <p class="fs-3 text-white">More like this:
            {% for ss in similar_songs %}
        <div class="row justify-content-between my-3 border-bottom border-white">
            <div class="col-2 p-2">
                <img src="{{ ss.poster.url }}" class="w-75">
            </div>
            <div class="col-6">
                <p class="text-white fs-5">
                    <a href="{{ ss.url_detail }}" class="text-white text-decoration-none">
                        {{ ss }}
                    </a>
                </p>
            </div>
            <div class="col-2">
                <p class="text-white fs-5">{{ ss.year }}</p>
            </div>
        </div>
        {% endfor %}
        </p>
    </div>
    <div class="col-6 pb-5">
        {% if song.comments.exists %}
        <p class="text-white fs-3">Comments:</p>
        {% for c in song.comments.all %}
        <p class="text-secondary">
            <img src="{{ c.user.addon.userpic.url }}" width="40" class="border border-white">
            <span class="text-white">{{ c.user }}: {{ c.text }}</span>
            {{ c.published|timesince }} ago
        </p>
        {% endfor %}
        <hr class="border border-secondary">
        {% endif %}
        {% if user.is_authenticated %}
        <form action="{% url 'rock:add-comment' pk=song.id %}" method="post">
            {% csrf_token %}
            {{ c_form }}
        </form>
        {% endif %}
    </div>
</div>


{% endblock %}

rock/templates/rock/song_list.html
{% extends 'rock/base.html' %}
{% load static %}

{% block title %}All Songs{% endblock %}

{% block main %}

<p class="text-black fs-3">All Songs</p>

<div class="row">
{% for s in object_list %}

<div class="col-4">
    <img src="{{ s.poster.url }}" class="h-75 w-100 rounded p-2 mb-1 border border-black">
    <p class="text-white fs-4">
        <img src="{% static 'rock/img/star.png' %}" width="30">
        {{ s.rating }}
    </p>
    <a href="{{ s.url_detail }}" class="text-decoration-none">
        <p class="text-white fs-5">{{ s.title }}</p>
    </a>
    {% if s.trailer %}
    <a href="https://youtu.be/{{ s.trailer }}" target="_blank" class="text-black text-decoration-none">
        <img src="{% static 'rock/img/play.png' %}" width="25">
        Watch trailer
    </a>
    {% endif %}
</div>
{% endfor %}
</div>

{% for contact in page_obj %}
{# Each "contact" is a Contact model object. #}
{{ contact.full_name|upper }}<br>

{% endfor %}

<div class="row justify-content-between mt-5">
    <div class="col-2 text-start">
        {% if page_obj.has_previous %}
        <a class="text-black text-decoration-none" href="?page=1"><b>&laquo; first</b></a>
        <a class="text-black text-decoration-none" href="?page={{ page_obj.previous_page_number }}"><b>previous</b></a>
        {% endif %}
    </div>
    <div class="col-2">
        <p class="text-black text-decoration-none">
            <b>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</b>
        </p>
    </div>
    <div class="col-2">
        {% if page_obj.has_next %}
        <a class="text-black text-decoration-none" href="?page={{ page_obj.next_page_number }}"><b>next</b></a>
        <a class="text-black text-decoration-none" href="?page={{ page_obj.paginator.num_pages }}"><b>last &raquo;</b></a>
        {% endif %}
    </div>
</div>

{% endblock %}